# Applications of Cartesian Products

In [39]:
import pandas as pd

## 1. Redo the excercises above but this time, show the Cartesian Product for data_2 $x$ data_1.
---

In [42]:
# Generate dataset A
data_1 = pd.DataFrame({'A':[3,4],'B':[5,6]})
data_1

   A  B
0  3  5
1  4  6

In [41]:
# Generate dataset B
data_2 = pd.DataFrame({'C':[7,8]})
data_2

   C
0  7
1  8

In [31]:
#Create Cartesian Product
data_3 = data_2.merge(data_1, how='cross')
data_3

   C  A  B
0  7  3  5
1  7  4  6
2  8  3  5
3  8  4  6

## 2. Reading and using CSV Files
---

In [37]:
# Reading CSV Files
longData_1 = pd.read_csv("electronic-card-transactions-july-2023.csv")
data_1 = longData_1.head(50)

longData_2 = pd.read_csv("wholesale-trade-survey-march-2023-quarter.csv")
data_2 = longData_2.head(50)

### 2.1 Show data_1 $x$ data_2

In [38]:
data_3 = data_1.merge(data_2, how='cross')
data_3

,Series_reference_x,Period_x,Data_value_x,Suppressed_x,STATUS_x,UNITS_x,Magnitude_x,Subject_x,Group_x,Series_title_1_x,...,STATUS_y,UNITS_y,Magnitude_y,Subject_y,Group_y,Series_title_1_y,Series_title_2_y,Series_title_3_y,Series_title_4_y,Series_title_5_y
0,ECTA.S19A1,2001.03,2462.5,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,...,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
1,ECTA.S19A1,2001.03,2462.5,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,...,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
2,ECTA.S19A1,2001.03,2462.5,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,...,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
3,ECTA.S19A1,2001.03,2462.5,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,...,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
4,ECTA.S19A1,2001.03,2462.5,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,...,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,ECTA.S19A9,2004.03,36878.7,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,...,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
2496,ECTA.S19A9,2004.03,36878.7,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,...,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
2497,ECTA.S19A9,2004.03,36878.7,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,...,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
2498,ECTA.S19A9,2004.03,36878.7,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,...,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
2499,ECTA.S19A9,2004.03,36878.7,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,...,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN

### 2.2 Show data_2 $x$ data_1

In [34]:
data_4 = data_2.merge(data_1, how='cross')
data_4

,Series_reference_x,Period_x,Data_value_x,Suppressed_x,STATUS_x,UNITS_x,Magnitude_x,Subject_x,Group_x,Series_title_1_x,...,STATUS_y,UNITS_y,Magnitude_y,Subject_y,Group_y,Series_title_1_y,Series_title_2_y,Series_title_3_y,Series_title_4_y,Series_title_5_y
0,WTSQ.SFA1CA,1995.03,2368.69,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,...,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
1,WTSQ.SFA1CA,1995.03,2368.69,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,...,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
2,WTSQ.SFA1CA,1995.03,2368.69,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,...,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
3,WTSQ.SFA1CA,1995.03,2368.69,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,...,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
4,WTSQ.SFA1CA,1995.03,2368.69,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,...,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,WTSQ.SFA1CA,2007.06,3590.18,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,...,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS core industries,NaN,NaN,NaN
2496,WTSQ.SFA1CA,2007.06,3590.18,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,...,C,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,Total,NaN,NaN,NaN
2497,WTSQ.SFA1CA,2007.06,3590.18,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,...,C,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,Total,NaN,NaN,NaN
2498,WTSQ.SFA1CA,2007.06,3590.18,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,...,C,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,Total,NaN,NaN,NaN
2499,WTSQ.SFA1CA,2007.06,3590.18,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,...,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,Total,NaN,NaN,NaN